sonata_user:
  security_acl: false
  manager_type: orm # can be orm or mongodb
  mailer: fos_user.mailer.twig_swift
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group
  profile:
    default_avatar: '/img/logo_small.png' # Default avatar displayed if the user doesn't have one
