<?php
/**
 * Created by PhpStorm.
 * User: beathan
 * Date: 2019-03-10
 * Time: 13:15
 */

namespace App\Admin;


use App\Entity\Currency;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\Filter\NumberType;
use Sonata\AdminBundle\Route\RouteCollection;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class CurrencyRatesAdmin extends AbstractAdmin
{
    protected $baseRouteName='currency_rates';
    protected $baseRoutePattern = 'currency_rates';

    protected function configureRoutes(RouteCollection $collection)
    {
        parent::configureRoutes($collection); // TODO: Change the autogenerated stub

        $collection->remove('create');
        $collection->remove('batch');
        $collection->remove('delete');
        $collection->remove('export');
        return $collection;
    }


    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->with('Content');
        $formMapper->add('rateBuy', TextType::class);
        $formMapper->add('rateSell', TextType::class);
        $formMapper->add('reserve', TextType::class);

    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
        $datagridMapper->add('rateBuy');
        $datagridMapper->add('rateSell');
        $datagridMapper->add('reserve');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->addIdentifier('name');
        $listMapper->add('rateBuy');
        $listMapper->add('rateSell');
        $listMapper->add('reserve');

    }

    public function toString($object)
    {
        return $object instanceof Currency
            ? $object->getName()
            : 'Currency'; // shown in the breadcrumb on the create view
    }

}
